<?php
echo '<!doctype html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '';
echo '<meta name="description" content="">';
echo '<meta name="author" content="TemplateMo">';
echo '';
echo '<title>ProjectMate official</title>';
echo '';
echo '<!-- CSS FILES -->';
echo '<link rel="preconnect" href="https://fonts.googleapis.com">';
echo '';
echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>';
echo '';
echo '<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet">';
echo '';
echo '<link href="css/bootstrap.min.css" rel="stylesheet">';
echo '';
echo '<link href="css/bootstrap-icons.css" rel="stylesheet">';
echo '';
echo '<link href="css/magnific-popup.css" rel="stylesheet">';
echo '';
echo '<link href="css/templatemo-first-portfolio-style.css" rel="stylesheet">';
echo '';
echo '<!--';
echo '';
echo 'TemplateMo 578 First Portfolio';
echo '';
echo 'https://templatemo.com/tm-578-first-portfolio';
echo '';
echo '-->';
echo '</head>';
echo '';
echo '<body>';
echo '';
echo '<section class="preloader">';
echo '<div class="spinner">';
echo '<span class="spinner-rotate"></span>';
echo '</div>';
echo '</section>';
echo '';
echo '<nav class="navbar navbar-expand-lg">';
echo '<div class="container">';
echo '';
echo '<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '';
echo '<a href="MainHome.php" class="navbar-brand mx-auto mx-lg-0">ProjectMate</a>';
echo '';
echo '<div class="d-flex align-items-center d-lg-none">';
echo '<i class="navbar-icon bi-telephone-plus me-3"></i>';
echo '<a class="custom-btn btn" href="#section_5">';
echo '+91 8078450285';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="collapse navbar-collapse" id="navbarNav">';
echo '<ul class="navbar-nav ms-lg-5">';
echo '<li class="nav-item">';
echo '<a class="nav-link click-scroll" href="#section_1">Home</a>';
echo '</li>';
echo '';
echo '<li class="nav-item">';
echo '<a class="nav-link click-scroll" href="#section_2">About</a>';
echo '</li>';
echo '';
echo '<li class="nav-item">';
echo '<a class="nav-link click-scroll" href="#section_3">Services</a>';
echo '</li>';
echo '';
echo '<li class="nav-item">';
echo '<a class="nav-link click-scroll" href="#section_5">Contact</a>';
echo '</li>';
echo '</ul>';
echo '';
echo '</div>';
echo '</nav>';
echo '';
echo '<main>';
echo '';
echo '</section>';
echo '';
echo '';
echo '<section class="about section-padding" id="section_2">';
echo '<div class="container">';
echo '<div class="row">';
echo '';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section class="featured section-padding">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-6 col-12 mt-5 mt-lg-0">';
echo '<div class="about-thumb">';
echo '<div class="row">';
echo '';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '';
echo '<section class="clients section-padding">';
echo '<div class="container">';
echo '<div class="row align-items-center">';
echo '';
echo '<div class="col-lg-12 col-12">';
echo '<h3 class="text-center mb-5">Add Additional Tools</h3>';
echo '</div>';
echo '';
echo '<div class="col-lg-2 col-4 ms-auto clients-item-height">';
echo '<img src="images/clients/gitgub1.svg" class="clients-image img-fluid" alt="">';
echo '</div>';
echo '';
echo '<div class="col-lg-2 col-4 clients-item-height">';
echo '<img src="images/clients/chatgpt.svg" class="clients-image img-fluid" alt="">';
echo '</div>';
echo '';
echo '<div class="col-lg-2 col-4 clients-item-height">';
echo '<img src="images/clients/amazon.svg" class="clients-image img-fluid" alt="">';
echo '</div>';
echo '';
echo '<div class="col-lg-2 col-4 clients-item-height">';
echo '<img src="images/clients/docs.svg" class="clients-image img-fluid" alt="">';
echo '</div>';
echo '';
echo '<div class="col-lg-2 col-4 me-auto clients-item-height">';
echo '<img src="images/clients/bootstrp.svg" class="clients-image img-fluid" alt="">';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '';
echo '<section class="services section-padding" id="section_3">';
echo '<div class="container">';
echo '<div class="row">';
echo '';
echo '<section class="contact section-padding" id="section_5">';
echo '<div class="container">';
echo '<div class="row">';
echo '';
echo '<div class="col-lg-6 col-md-8 col-12">';
echo '<div class="section-title-wrap d-flex justify-content-center align-items-center mb-5">';
echo '<img src="images/1logo.png" class="avatar-image img-fluid" alt="">';
echo '';
echo '<h2 class="text-white ms-4 mb-0">Say Hi</h2>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="clearfix"></div>';
echo '';
echo '<div class="col-lg-3 col-md-6 col-12 pe-lg-0">';
echo '<div class="contact-info contact-info-border-start d-flex flex-column">';
echo '<strong class="site-footer-title d-block mb-3">Services</strong>';
echo '';
echo '<ul class="footer-menu">';
echo '<li class="footer-menu-item"><a href="#" class="footer-menu-link">Collage Project Management</a></li>';
echo '';
echo '<li class="footer-menu-item"><a href="#" class="footer-menu-link">Task Management</a></li>';
echo '';
echo '<li class="footer-menu-item"><a href="#" class="footer-menu-link">ChatHub</a></li>';
echo '';
echo '<li class="footer-menu-item"><a href="#" class="footer-menu-link">Tracking</a></li>';
echo '</ul>';
echo '';
echo '<strong class="site-footer-title d-block mt-4 mb-3">Stay connected</strong>';
echo '';
echo '<ul class="social-icon">';
echo '<li class="social-icon-item"><a href="https://twitter.com/minthu" class="social-icon-link bi-twitter"></a></li>';
echo '';
echo '<li class="social-icon-item"><a href="#" class="social-icon-link bi-instagram"></a></li>';
echo '';
echo '<li class="social-icon-item"><a href="#" class="social-icon-link bi-pinterest"></a></li>';
echo '';
echo '<li class="social-icon-item"><a href="https://www.youtube.com/templatemo" class="social-icon-link bi-youtube"></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-md-6 col-12 ps-lg-0">';
echo '<div class="contact-info d-flex flex-column">';
echo '<strong class="site-footer-title d-block mb-3">About</strong>';
echo '';
echo '<p class="mb-2">';
echo 'ProjectMate Is A Collage Project Management System.';
echo '</p>';
echo '';
echo '<strong class="site-footer-title d-block mt-4 mb-3">Email</strong>';
echo '';
echo '<p>';
echo '<a href="mailto:projectMate@info">';
echo 'projectMate@info';
echo '</a>';
echo '</p>';
echo '';
echo '<strong class="site-footer-title d-block mt-4 mb-3">Call</strong>';
echo '';
echo '<p class="mb-0">';
echo '<a href="tel: +91 8078152585">';
echo '+91 8078152585';
echo '</a>';
echo '</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-6 col-12 mt-5 mt-lg-0">';
echo '<form action="#" method="get" class="custom-form contact-form" role="form">';
echo '<div class="row">';
echo '<div class="col-lg-6 col-md-6 col-12">';
echo '<div class="form-floating">';
echo '<input type="text" name="name" id="name" class="form-control" placeholder="Name" required="">';
echo '';
echo '<label for="floatingInput">Name</label>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-6 col-md-6 col-12">';
echo '<div class="form-floating">';
echo '<input type="email" name="email" id="email" pattern="[^ @]*@[^ @]*" class="form-control" placeholder="Email address" required="">';
echo '';
echo '<label for="floatingInput">Email address</label>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-md-6 col-6">';
echo '<div class="form-check form-check-inline">';
echo '<input name="website" type="checkbox" class="form-check-input" id="inlineCheckbox1" value="1">';
echo '';
echo '<label class="form-check-label" for="inlineCheckbox1">';
echo '<i class="bi-globe form-check-icon"></i>';
echo '<span class="form-check-label-text">Websites</span>';
echo '</label>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-md-6 col-6">';
echo '<div class="form-check form-check-inline">';
echo '<input name="branding" type="checkbox" class="form-check-input" id="inlineCheckbox2" value="1">';
echo '';
echo '<label class="form-check-label" for="inlineCheckbox2">';
echo '<i class="bi-lightbulb form-check-icon"></i>';
echo '<span class="form-check-label-text">Android Apps</span>';
echo '</label>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-md-6 col-6">';
echo '<div class="form-check form-check-inline">';
echo '<input name="ecommerce" type="checkbox" class="form-check-input" id="inlineCheckbox3" value="1">';
echo '';
echo '<label class="form-check-label" for="inlineCheckbox3">';
echo '<i class="bi-phone form-check-icon"></i>';
echo '<span class="form-check-label-text">DataBase</span>';
echo '</label>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-md-6 col-6">';
echo '<div class="form-check form-check-inline me-0">';
echo '<input name="seo" type="checkbox" class="form-check-input" id="inlineCheckbox4" value="1">';
echo '';
echo '<label class="form-check-label" for="inlineCheckbox4">';
echo '<i class="bi-google form-check-icon"></i>';
echo '<span class="form-check-label-text">UI/UX</span>';
echo '</label>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-12 col-12">';
echo '<div class="form-floating">';
echo '<textarea class="form-control" id="message" name="message" placeholder="Tell me about the project"></textarea>';
echo '';
echo '<label for="floatingTextarea">Tell us about the project</label>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-12 ms-auto">';
echo '<button type="submit" class="form-control">Send</button>';
echo '</div>';
echo '';
echo '</div>';
echo '</form>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '</main>';
echo '';
echo '<footer class="site-footer">';
echo '<div class="container">';
echo '<div class="row">';
echo '';
echo '<div class="col-lg-12 col-12">';
echo '<div class="copyright-text-wrap">';
echo '<p class="mb-0">';
echo '<span class="copyright-text">Copyright © 2036 <a href="#">ProjectMate/a> Company. All rights reserved.</span>';
echo 'Design:';
echo '<a rel="sponsored" href="https://templatemo.com" target="_blank">TemplateMo</a>';
echo '</p>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</footer>';
echo '';
echo '<!-- JAVASCRIPT FILES -->';
echo '<script src="js/jquery.min.js"></script>';
echo '<script src="js/bootstrap.min.js"></script>';
echo '<script src="js/jquery.sticky.js"></script>';
echo '<script src="js/click-scroll.js"></script>';
echo '<script src="js/jquery.magnific-popup.min.js"></script>';
echo '<script src="js/magnific-popup-options.js"></script>';
echo '<script src="js/custom.js"></script>';
echo '';
echo '</body>';
echo '</html>';
?>