<?php
echo '<!doctype html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '';
echo '<meta name="description" content="">';
echo '<meta name="author" content="TemplateMo">';
echo '';
echo '<title>ProjectMate Offical</title>';
echo '';
echo '<!-- CSS FILES -->';
echo '<link rel="preconnect" href="https://fonts.googleapis.com">';
echo '';
echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>';
echo '';
echo '<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet">';
echo '';
echo '<link href="css/bootstrap.min.css" rel="stylesheet">';
echo '';
echo '<link href="css/bootstrap-icons.css" rel="stylesheet">';
echo '';
echo '<link href="css/magnific-popup.css" rel="stylesheet">';
echo '';
echo '<link href="css/templatemo-first-portfolio-style.css" rel="stylesheet">';
echo '';
echo '<!--';
echo '';
echo 'TemplateMo 578 First Portfolio';
echo '';
echo 'https://templatemo.com/tm-578-first-portfolio';
echo '';
echo '-->';
echo '</head>';
echo '';
echo '<body>';
echo '';
echo '<section class="preloader">';
echo '<div class="spinner">';
echo '<span class="spinner-rotate"></span>';
echo '</div>';
echo '</section>';
echo '';
echo '<nav class="navbar navbar-expand-lg">';
echo '<div class="container">';
echo '';
echo '<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '';
echo '<a href="MainHome.php" class="navbar-brand mx-auto mx-lg-0">ProjectMate</a>';
echo '';
echo '<div class="d-flex align-items-center d-lg-none">';
echo '<i class="navbar-icon bi-telephone-plus me-3"></i>';
echo '<a class="custom-btn btn" href="#section_5">';
echo '+91 8078450285';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="collapse navbar-collapse" id="navbarNav">';
echo '<ul class="navbar-nav ms-lg-5">';
echo '<li class="nav-item">';
echo '<a class="nav-link click-scroll" href="#section_1">Home</a>';
echo '</li>';
echo '';
echo '<li class="nav-item">';
echo '<a class="nav-link click-scroll" href="#section_2">About</a>';
echo '</li>';
echo '';
echo '<li class="nav-item">';
echo '<a class="nav-link click-scroll" href="#section_3">Services</a>';
echo '</li>';
echo '';
echo '<li class="nav-item">';
echo '<a class="nav-link click-scroll" href="#section_5">Contact</a>';
echo '</li>';
echo '</ul>';
echo '';
echo '<div class="d-lg-flex align-items-center d-none ms-auto">';
echo '<i class="navbar-icon bi-telephone-plus me-3"></i>';
echo '<a class="custom-btn btn" href="#section_5">';
echo '+91 8078450285';
echo '</a>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</nav>';
echo '';
echo '<main>';
echo '';
echo '<section class="hero d-flex justify-content-center align-items-center" id="section_1">';
echo '<div class="container">';
echo '<div class="row">';
echo '';
echo '<div class="col-lg-7 col-12">';
echo '<div class="hero-text">';
echo '<div class="hero-title-wrap d-flex align-items-center mb-4">';
echo '<img src="images/1logo.png" class="avatar-image avatar-image-large img-fluid" alt="">';
echo '';
echo '<h1 class="hero-title ms-3 mb-0">Hey Everyone!</h1>';
echo '</div>';
echo '';
echo '<h2 class="mb-4">Welcome To ProjectMate.</h2>';
echo '<p class="mb-4"><a class="custom-btn btn custom-link" href="register.php">Get Started</a></p>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-5 col-12 position-relative">';
echo '<div class="hero-image-wrap"></div>';
echo '<img src="images/portrait-happy-excited-man-holding-laptop-computer.png" class="hero-image img-fluid" alt="">';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#535da1" fill-opacity="1" d="M0,160L24,160C48,160,96,160,144,138.7C192,117,240,75,288,64C336,53,384,75,432,106.7C480,139,528,181,576,208C624,235,672,245,720,240C768,235,816,213,864,186.7C912,160,960,128,1008,133.3C1056,139,1104,181,1152,202.7C1200,224,1248,224,1296,197.3C1344,171,1392,117,1416,90.7L1440,64L1440,0L1416,0C1392,0,1344,0,1296,0C1248,0,1200,0,1152,0C1104,0,1056,0,1008,0C960,0,912,0,864,0C816,0,768,0,720,0C672,0,624,0,576,0C528,0,480,0,432,0C384,0,336,0,288,0C240,0,192,0,144,0C96,0,48,0,24,0L0,0Z"></path></svg>';
echo '</section>';
echo '';
echo '';
echo '<section class="about section-padding" id="section_2">';
echo '<div class="container">';
echo '<div class="row">';
echo '';
echo '<div class="col-lg-6 col-12">';
echo '<img src="images/projectmanagement.png" class="about-image img-fluid" alt="">';
echo '</div>';
echo '';
echo '<div class="col-lg-6 col-12 mt-5 mt-lg-0">';
echo '<div class="about-thumb">';
echo '';
echo '<div class="section-title-wrap d-flex justify-content-end align-items-center mb-4">';
echo '<h2 class="text-white me-4 mb-0">ProjectMate</h2>';
echo '';
echo '<img src="images/1logo.png" class="avatar-image img-fluid" alt="">';
echo '</div>';
echo '';
echo '<h3 class="pt-2 mb-3">A little bit about us</h3>';
echo '';
echo '<p>ProjectMate  is a comprehensive and user-friendly web application platform designed to streamline and enhance project management for students.</p>';
echo '';
echo '<p>We provide a centralized hub for students to plan, organize, and collaborate  their academic projects effectively.</p>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section class="featured section-padding">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-6 col-12 mt-5 mt-lg-0">';
echo '<div class="about-thumb">';
echo '<div class="row">';
echo '<div class="col-lg-6 col-6 featured-border-bottom py-2">';
echo '<strong class="featured-numbers">05+</strong>';
echo '';
echo '<p class="featured-text">Years of Experiences</p>';
echo '</div>';
echo '';
echo '<div class="col-lg-6 col-6 featured-border-start featured-border-bottom ps-5 py-2">';
echo '<strong class="featured-numbers">245</strong>';
echo '';
echo '<p class="featured-text">Happy Students</p>';
echo '</div>';
echo '';
echo '<div class="col-lg-6 col-6 pt-4">';
echo '<strong class="featured-numbers">120</strong>';
echo '';
echo '<p class="featured-text">Project Finished</p>';
echo '</div>';
echo '';
echo '<div class="col-lg-6 col-6 featured-border-start ps-5 pt-4">';
echo '<strong class="featured-numbers">72+</strong>';
echo '';
echo '<p class="featured-text">Digital Awards</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '';
echo '<section class="clients section-padding">';
echo '<div class="container">';
echo '<div class="row align-items-center">';
echo '';
echo '<div class="col-lg-12 col-12">';
echo '<h3 class="text-center mb-5">Tools We Integrate</h3>';
echo '</div>';
echo '';
echo '<div class="col-lg-2 col-4 ms-auto clients-item-height">';
echo '<img src="images/clients/gitgub1.svg" class="clients-image img-fluid" alt="">';
echo '</div>';
echo '';
echo '<div class="col-lg-2 col-4 clients-item-height">';
echo '<img src="images/clients/chatgpt.svg" class="clients-image img-fluid" alt="">';
echo '</div>';
echo '';
echo '<div class="col-lg-2 col-4 clients-item-height">';
echo '<img src="images/clients/amazon.svg" class="clients-image img-fluid" alt="">';
echo '</div>';
echo '';
echo '<div class="col-lg-2 col-4 clients-item-height">';
echo '<img src="images/clients/docs.svg" class="clients-image img-fluid" alt="">';
echo '</div>';
echo '';
echo '<div class="col-lg-2 col-4 me-auto clients-item-height">';
echo '<img src="images/clients/bootstrp.svg" class="clients-image img-fluid" alt="">';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '';
echo '<section class="services section-padding" id="section_3">';
echo '<div class="container">';
echo '<div class="row">';
echo '';
echo '<div class="col-lg-10 col-12 mx-auto">';
echo '<div class="section-title-wrap d-flex justify-content-center align-items-center mb-5">';
echo '<img src="images/handshake-man-woman-after-signing-business-contract-closeup.jpg" class="avatar-image img-fluid" alt="">';
echo '';
echo '<h2 class="text-white ms-4 mb-0">Services</h2>';
echo '</div>';
echo '';
echo '<div class="row pt-lg-5">';
echo '<div class="col-lg-6 col-12">';
echo '<div class="services-thumb">';
echo '<div class="d-flex flex-wrap align-items-center border-bottom mb-4 pb-3">';
echo '<h3 class="mb-0">Collage Project Management</h3>';
echo '';
echo '<div class="services-price-wrap ms-auto">';
echo '<p class="services-price-text mb-0">$free</p>';
echo '<div class="services-price-overlay"></div>';
echo '</div>';
echo '</div>';
echo '';
echo '<p>This App Provides a Workspace For Students and Faculties can Monitor it Daily.</p>';
echo '';
echo '<a href="#" class="custom-btn custom-border-btn btn mt-3">Discover More</a>';
echo '';
echo '<div class="services-icon-wrap d-flex justify-content-center align-items-center">';
echo '<i class="services-icon bi-globe"></i>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-6 col-12">';
echo '<div class="services-thumb services-thumb-up">';
echo '<div class="d-flex flex-wrap align-items-center border-bottom mb-4 pb-3">';
echo '<h3 class="mb-0">Task Management</h3>';
echo '';
echo '<div class="services-price-wrap ms-auto">';
echo '<p class="services-price-text mb-0">$free</p>';
echo '<div class="services-price-overlay"></div>';
echo '</div>';
echo '</div>';
echo '';
echo '<p>Allow To Divide The Daily Works By Assigning ToDo Tasks.</p>';
echo '';
echo '<a href="#" class="custom-btn custom-border-btn btn mt-3">Discover More</a>';
echo '';
echo '<div class="services-icon-wrap d-flex justify-content-center align-items-center">';
echo '<i class="services-icon bi-lightbulb"></i>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-6 col-12">';
echo '<div class="services-thumb">';
echo '<div class="d-flex flex-wrap align-items-center border-bottom mb-4 pb-3">';
echo '<h3 class="mb-0">ChatHub</h3>';
echo '';
echo '<div class="services-price-wrap ms-auto">';
echo '<p class="services-price-text mb-0">$free</p>';
echo '<div class="services-price-overlay"></div>';
echo '</div>';
echo '</div>';
echo '';
echo '<p>Provides A Space For Community And Private Chats.</p>';
echo '';
echo '<a href="#" class="custom-btn custom-border-btn btn mt-3">Discover More</a>';
echo '';
echo '<div class="services-icon-wrap d-flex justify-content-center align-items-center">';
echo '<i class="services-icon bi-phone"></i>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-6 col-12">';
echo '<div class="services-thumb services-thumb-up">';
echo '<div class="d-flex flex-wrap align-items-center border-bottom mb-4 pb-3">';
echo '<h3 class="mb-0">Tracking</h3>';
echo '';
echo '<div class="services-price-wrap ms-auto">';
echo '<p class="services-price-text mb-0">$free</p>';
echo '<div class="services-price-overlay"></div>';
echo '</div>';
echo '</div>';
echo '';
echo '<p>Allows Students And Teachers To Track And Update All Events Of The Project.</p>';
echo '';
echo '<a href="#" class="custom-btn custom-border-btn btn mt-3">Discover More</a>';
echo '';
echo '<div class="services-icon-wrap d-flex justify-content-center align-items-center">';
echo '<i class="services-icon bi-google"></i>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section class="contact section-padding" id="section_5">';
echo '<div class="container">';
echo '<div class="row">';
echo '';
echo '<div class="col-lg-6 col-md-8 col-12">';
echo '<div class="section-title-wrap d-flex justify-content-center align-items-center mb-5">';
echo '<img src="images/1logo.png" class="avatar-image img-fluid" alt="">';
echo '';
echo '<h2 class="text-white ms-4 mb-0">Say Hi</h2>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="clearfix"></div>';
echo '';
echo '<div class="col-lg-3 col-md-6 col-12 pe-lg-0">';
echo '<div class="contact-info contact-info-border-start d-flex flex-column">';
echo '<strong class="site-footer-title d-block mb-3">Services</strong>';
echo '';
echo '<ul class="footer-menu">';
echo '<li class="footer-menu-item"><a href="#" class="footer-menu-link">Collage Project Management</a></li>';
echo '';
echo '<li class="footer-menu-item"><a href="#" class="footer-menu-link">Task Management</a></li>';
echo '';
echo '<li class="footer-menu-item"><a href="#" class="footer-menu-link">ChatHub</a></li>';
echo '';
echo '<li class="footer-menu-item"><a href="#" class="footer-menu-link">Tracking</a></li>';
echo '</ul>';
echo '';
echo '<strong class="site-footer-title d-block mt-4 mb-3">Stay connected</strong>';
echo '';
echo '<ul class="social-icon">';
echo '<li class="social-icon-item"><a href="https://twitter.com/minthu" class="social-icon-link bi-twitter"></a></li>';
echo '';
echo '<li class="social-icon-item"><a href="#" class="social-icon-link bi-instagram"></a></li>';
echo '';
echo '<li class="social-icon-item"><a href="#" class="social-icon-link bi-pinterest"></a></li>';
echo '';
echo '<li class="social-icon-item"><a href="https://www.youtube.com/templatemo" class="social-icon-link bi-youtube"></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-md-6 col-12 ps-lg-0">';
echo '<div class="contact-info d-flex flex-column">';
echo '<strong class="site-footer-title d-block mb-3">About</strong>';
echo '';
echo '<p class="mb-2">';
echo 'ProjectMate Is A Collage Project Management System.';
echo '</p>';
echo '';
echo '<strong class="site-footer-title d-block mt-4 mb-3">Email</strong>';
echo '';
echo '<p>';
echo '<a href="mailto:projectmate25@gmail.com">';
echo 'projectmate25@gmail.com';
echo '</a>';
echo '</p>';
echo '';
echo '<strong class="site-footer-title d-block mt-4 mb-3">Call</strong>';
echo '';
echo '<p class="mb-0">';
echo '<a href="tel: +91 8078152585">';
echo '+91 8078152585';
echo '</a>';
echo '</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-6 col-12 mt-5 mt-lg-0">';
echo '<form action="#" method="get" class="custom-form contact-form" role="form">';
echo '<div class="row">';
echo '<div class="col-lg-6 col-md-6 col-12">';
echo '<div class="form-floating">';
echo '<input type="text" name="name" id="name" class="form-control" placeholder="Name" required="">';
echo '';
echo '<label for="floatingInput">Name</label>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-6 col-md-6 col-12">';
echo '<div class="form-floating">';
echo '<input type="email" name="email" id="email" pattern="[^ @]*@[^ @]*" class="form-control" placeholder="Email address" required="">';
echo '';
echo '<label for="floatingInput">Email address</label>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-md-6 col-6">';
echo '<div class="form-check form-check-inline">';
echo '<input name="website" type="checkbox" class="form-check-input" id="inlineCheckbox1" value="1">';
echo '';
echo '<label class="form-check-label" for="inlineCheckbox1">';
echo '<i class="bi-globe form-check-icon"></i>';
echo '<span class="form-check-label-text">Websites</span>';
echo '</label>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-md-6 col-6">';
echo '<div class="form-check form-check-inline">';
echo '<input name="branding" type="checkbox" class="form-check-input" id="inlineCheckbox2" value="1">';
echo '';
echo '<label class="form-check-label" for="inlineCheckbox2">';
echo '<i class="bi-lightbulb form-check-icon"></i>';
echo '<span class="form-check-label-text">Android Apps</span>';
echo '</label>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-md-6 col-6">';
echo '<div class="form-check form-check-inline">';
echo '<input name="ecommerce" type="checkbox" class="form-check-input" id="inlineCheckbox3" value="1">';
echo '';
echo '<label class="form-check-label" for="inlineCheckbox3">';
echo '<i class="bi-phone form-check-icon"></i>';
echo '<span class="form-check-label-text">DataBase</span>';
echo '</label>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-md-6 col-6">';
echo '<div class="form-check form-check-inline me-0">';
echo '<input name="seo" type="checkbox" class="form-check-input" id="inlineCheckbox4" value="1">';
echo '';
echo '<label class="form-check-label" for="inlineCheckbox4">';
echo '<i class="bi-google form-check-icon"></i>';
echo '<span class="form-check-label-text">UI/UX</span>';
echo '</label>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-12 col-12">';
echo '<div class="form-floating">';
echo '<textarea class="form-control" id="message" name="message" placeholder="Tell me about the project"></textarea>';
echo '';
echo '<label for="floatingTextarea">Tell us about the project</label>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-12 ms-auto">';
echo '<button type="submit" class="form-control">Send</button>';
echo '</div>';
echo '';
echo '</div>';
echo '</form>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '</main>';
echo '';
echo '<footer class="site-footer">';
echo '<div class="container">';
echo '<div class="row">';
echo '';
echo '<div class="col-lg-12 col-12">';
echo '<div class="copyright-text-wrap">';
echo '<p class="mb-0">';
echo '<span class="copyright-text">Copyright © 2036 <a href="#">ProjectMate/a> Company. All rights reserved.</span>';
echo 'Design:';
echo '<a rel="sponsored" href="https://templatemo.com" target="_blank">TemplateMo</a>';
echo '</p>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</footer>';
echo '';
echo '<!-- JAVASCRIPT FILES -->';
echo '<script src="js/jquery.min.js"></script>';
echo '<script src="js/bootstrap.min.js"></script>';
echo '<script src="js/jquery.sticky.js"></script>';
echo '<script src="js/click-scroll.js"></script>';
echo '<script src="js/jquery.magnific-popup.min.js"></script>';
echo '<script src="js/magnific-popup-options.js"></script>';
echo '<script src="js/custom.js"></script>';
echo '';
echo '</body>';
echo '</html>';
?>